#include "pitches.h"

// Define note durations

// Define note durations
#define EIGHTH 250
#define QUARTER 500
#define HALF 1000
#define WHOLE 2000

// Define the melody for "Bad Apple!!"
int badAppleMelody[] = {
    NOTE_A4, NOTE_E5, NOTE_D5, NOTE_F5, NOTE_D5, NOTE_E5, NOTE_A4, NOTE_G4, NOTE_A4, NOTE_C5,
    NOTE_A4, NOTE_E5, NOTE_D5, NOTE_F5, NOTE_D5, NOTE_E5, NOTE_A4, NOTE_G4, NOTE_A4, NOTE_C5,
    NOTE_D5, NOTE_E5, NOTE_A5, NOTE_A4, NOTE_E5, NOTE_D5, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_A4,
    NOTE_D5, NOTE_G4, NOTE_A4, NOTE_E5, NOTE_D5, NOTE_E5, NOTE_A4, NOTE_A5, NOTE_A5, NOTE_E5,
    NOTE_D5, NOTE_C5, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_A4, NOTE_A4, NOTE_A4, NOTE_G4,
    NOTE_A4, NOTE_E5, NOTE_D5, NOTE_F5, NOTE_D5, NOTE_E5, NOTE_A4, NOTE_G4, NOTE_A4, NOTE_C5,
};

int badAppleDurations[] = {
    QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, HALF, EIGHTH, EIGHTH, QUARTER,
    QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, HALF, EIGHTH, EIGHTH, QUARTER,
    QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, HALF,
    EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, HALF, EIGHTH, EIGHTH, QUARTER,
    QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, HALF, EIGHTH, EIGHTH, QUARTER,
    QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, HALF, QUARTER, EIGHTH, HALF,
};

void setup() {}

void loop() {
    for (int i = 0; i < sizeof(badAppleMelody) / sizeof(badAppleMelody[0]); i++) {
        tone(8, badAppleMelody[i], badAppleDurations[i]);
        delay(badAppleDurations[i]);
    }
}
